version: 2
jobs:
  build:
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run:
          name: Run tests 
          command: swift test 

workflows:
  version: 2
  ndlogger:
    jobs:
      - build
